_include: !include hackBase.yaml

data_train_view_files: ['hack/trainConfigs/supervised_train_v02.txt', ]   # relative path to the train view file lists
data_val_bin_path: ['hack/music-detection-data/sl_training_set_v1/']  # relative path to the binary data files
data_val_view_files: ['hack/trainConfigs/supervised_val_v02.txt']   # relative path to the train view file lists

epochs: 10000
batch_size: 2048
workers: 8
data_epoch_checkpoint_freq: 1
early_stop_patience: 10
print_freq: 1
plot_freq: 1
operations: [train_supervised]
debug: True

# To use a torchvision Net
backbone_model: resnet50
backbone_kwargs: [{ "zero_init_residual": True}]

checkpoint_name: ""
